name = "bryant-construction-leads"
main = "worker.js"
compatibility_date = "2026-07-15"

[vars]
LEAD_EMAIL = "ajbryantsleads@gmail.com"

[[routes]]
pattern = "bryantconstruct.com/api/*"
zone_name = "bryantconstruct.com"

[[routes]]
pattern = "bryantconstructiongroup.co.uk/api/*"
zone_name = "bryantconstructiongroup.co.uk"

[[r2_buckets]]
binding = "CONTACT_UPLOADS"
bucket_name = "contact-us-form-image-upload-construction"
